Removed Leo from GitOps CODEOWNERS
cncf/tag-app-delivery pull request #177
Opened 2022-01-17 07:57 UTC by thschue

2022-01-17 15:37 UTC, AlexsJones approved these changes

2022-01-19 01:03 UTC, scottrigby requested changes
@thschue Hi, we currently still have all the [maintainers of OpenGitOps](https://github.com/open-gitops/project/blob/main/MAINTAINERS) as codeowners of the `gitops-wg` directory. Leo has stepped down as a co-chair, but is still a maintainer. So we should not merge this PR. Thank you

2022-02-02 12:04 UTC, AloisReitbauer approved these changes

2022-02-02 12:04 UTC, AloisReitbauer approved these changes

2022-03-28 08:53 UTC, merged