Update interested-parties.md
cncf/tag-app-delivery pull request #215
Opened 2022-05-05 03:29 UTC by dnielsen

added my name and company: Dave Nielsen | Harness

2022-06-21 08:29 UTC, oleg-nenashev approved these changes

2022-07-23 20:44 UTC, scottrigby requested changes

2022-07-23 20:44 UTC, scottrigby commented on gitops-wg/interested-parties.md
> +Harness | Dave Nielsen
We're asking folks to please add their GitHub username going forward. Thanks!

```suggestion
Harness | Dave Nielsen | dnielsen
```

2022-07-24 16:11 UTC, dnielsen commented
Thanks scottrigby!

2022-07-24 16:11 UTC, closed without merging