Add Keda to list of platform components
cncf/tag-app-delivery pull request #385
Opened 2023-04-24 21:54 UTC by niklasbeinghaus

- Infrastructure services
- Messaging and event services

Issue: #378

2023-04-25 06:08 UTC, tomkerkhove requested changes
Sorry for the massive nits but we have to follow KEDA's branding guidelines - https://github.com/kedacore/governance/blob/main/BRANDING.md

2023-04-25 06:08 UTC, tomkerkhove commented on platforms-whitepaper/latest/index.md
> +    <td>Kubernetes, Kubevirt, Knative, WasmEdge, Keda<br />CNI, Istio, Cilium, Envoy, Linkerd, CoreDNS<br />Rook, Longhorn, Etcd</td>
```suggestion
    <td>Kubernetes, Kubevirt, Knative, WasmEdge, KEDA<br />CNI, Istio, Cilium, Envoy, Linkerd, CoreDNS<br />Rook, Longhorn, Etcd</td>
```

2023-04-25 06:08 UTC, tomkerkhove commented on platforms-whitepaper/latest/index.md
> +    <td>Strimzi, NATS, gRPC, Knative, Dapr, Keda</td>
```suggestion
    <td>Strimzi, NATS, gRPC, Knative, Dapr, KEDA</td>
```

2023-04-25 06:11 UTC, tomkerkhove commented
Sorry to be a pain, but wouldn't it be nice if we put autoscaling front and center by introducing a new category for it? Scalability is at the heart of cloud-native so I believe we should emphasize this here.

Not only to cover KEDA, but potentially other things such as Kubernetes Cluster Autoscaler or Karpenter.

Also, can we update this visual overview?

![image](https://user-images.githubusercontent.com/4345663/234189288-559effba-8c45-4ef2-916d-db035c9a0332.png)

2023-04-25 06:20 UTC, niklasbeinghaus commented
> Sorry to be a pain, but wouldn't it be nice if we put autoscaling front and center by introducing a new category for it? Scalability is at the heart of cloud-native so I believe we should emphasize this here.

I wasn't quite sure about the categories in this either, however from a platform engineering perspective, it makes sense to keep this condensed. What do you think about splitting the "automate" category and adding a "scaling" category thereunder?

> Also, can we update this visual overview?
Once we've found a solution for the right category, we should definitely update the visual overview as well.

2023-04-25 09:25 UTC, tomkerkhove commented
> I wasn't quite sure about the categories in this either, however from a platform engineering perspective, it makes sense to keep this condensed. What do you think about splitting the "automate" category and adding a "scaling" category thereunder?

Fine for me!

2023-04-26 22:20 UTC, joshgav commented
Hi @tomkerkhove, I lean to think (auto)scaling is a feature of whatever resource is being managed. Since KEDA scales compute infrastructure based on events it seems it's a feature of compute.

Karpenter and Cluster Autoscaler are interesting examples. Still, they're mostly focused on automatically scaling compute infrastructure and so probably belong with "Infrastructure". Do they also automate scaling of other resource types?

So I'd say for now let's put autoscalers together with the resource types they scale, in KEDA's case infrastructure/compute.

2023-04-26 22:23 UTC, joshgav requested changes
We've tried to list any given project only once to reduce clutter. Though it fits a bit under "events" too, I think the primary place for KEDA would be within infrastructure since it manages compute. Could you put it just in the infrastructure category? Thanks!

2023-04-27 12:42 UTC, zroubalik commented
> Hi @tomkerkhove, I lean to think (auto)scaling is a feature of whatever resource is being managed. Since KEDA scales compute infrastructure based on events it seems it's a feature of compute.
> 

Hey, it depends on what do you consider as `compute infrastructure`, KEDA scales workloads (apps - Deployments, Jobs...).

> Karpenter and Cluster Autoscaler are interesting examples. Still, they're mostly focused on automatically scaling compute infrastructure and so probably belong with "Infrastructure". Do they also automate scaling of other resource types?

These tools scales only compute nodes (k8s nodes) and if I am not mistaken Karpenter is AWS only.

2023-04-27 14:10 UTC, abangser commented
I would agree that this still feels like compute scaling. IMO deployments / jobs / CRDs are versions of compute, just like bare metal, VMs, and containers are versions of compute. We are getting better at abstractions, but at the end of the day my understanding is that KEDA helps manage higher load on the system by horizontally scaling the things that respond to those higher requests. Would be really helpful to understand if that is the wrong understanding though!

2023-04-27 15:54 UTC, zroubalik commented
> I would agree that this still feels like compute scaling. IMO deployments / jobs / CRDs are versions of compute, just like bare metal, VMs, and containers are versions of compute. We are getting better at abstractions, but at the end of the day my understanding is that KEDA helps manage higher load on the system by horizontally scaling the things that respond to those higher requests. Would be really helpful to understand if that is the wrong understanding though!

Yeah, that's completely correct understanding! As I mentioned, it depends on what do you see by `compute`, if it is what you just mentioned above, then we should be good.

2023-04-28 19:09 UTC, joshgav approved these changes
LGTM! Thanks for the productive discussion!

2023-04-28 19:10 UTC, merged