upt index.md for Korean
cncf/tag-app-delivery pull request #406
Opened 2023-05-04 06:52 UTC by sysnet4admin

Would you merge for korea version for index.md?

2023-05-19 20:13 UTC, joshgav commented
Thanks for this @sysnet4admin! Two things we need to do:

- Make sure we've set up the directory properly for Hugo to handle multiple languages, along the lines of https://github.com/cncf/tag-app-delivery/issues/394
- Check the translated version here with Google Translate for consistency

I'll work on the second one now and the first soon.

2023-05-19 20:18 UTC, joshgav commented
Here's a link that includes a Google Translate version for others that want to review: <https://github-com.translate.goog/cncf/tag-app-delivery/blob/2a1002a23187fa203525bcb81b2ad05d5956a72a/platforms-whitepaper/v1/index-ko.md?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp>

2023-05-19 20:31 UTC, joshgav requested changes
The text looks pretty good to me based on applying Google Translate! Can you change the name of the file per Hugo's guidelines and my comment?

@cjyabraham can you add `platforms-whitepaper/v1` to the paths which trigger a rebuild in Netlify? Thanks!

2023-05-19 20:31 UTC, joshgav commented on platforms-whitepaper/v1/index-ko.md
Per [these docs at the Hugo site](https://gohugo.io/content-management/multilingual/#translation-by-filename) this file needs to be named `index.ko.md` to be linked to `index.md`. Can you change that?

2023-05-20 05:50 UTC, cjyabraham commented on platforms-whitepaper/v1/index-ko.md
I don't know how to get netlify to watch a file outside of the `website` directory. Would you consider we restructure the whole repo so the website resides in the root and the whole repo can then be watched?

2023-05-20 08:17 UTC, sysnet4admin commented on platforms-whitepaper/v1/index-ko.md
Okay @joshgav. 
So may I PR again to change file name from `index-ko.md` to `index.ko.md` now? 
Because the structure of website directory is not clear yet.
Feel free to let me know how do I do.

2023-05-20 14:46 UTC, joshgav commented on platforms-whitepaper/v1/index-ko.md
Hi @sysnet4admin, yes please name the file `index.ko.md`, you can add a commit to this PR if you'd like.

Then @cjyabraham let's force a redeploy for this PR and check out the results (we'll figure out the triggering issue somewhere else).

Thank you!

2023-05-22 01:43 UTC, sysnet4admin commented on platforms-whitepaper/v1/index-ko.md
@joshgav 
Changed file name from `index-ko.md` to `index.ko.md` . 
Feel free to let you know further activity if it needs.

2023-05-22 17:17 UTC, joshgav commented
@cjyabraham could you force the preview to deploy for this PR?

Maybe we should just have it deploy for every PR for now, even outside the `website` dir.

2023-05-23 02:58 UTC, cjyabraham commented
> @cjyabraham could you force the preview to deploy for this PR?
> 
> Maybe we should just have it deploy for every PR for now, even outside the `website` dir.

Ok, here's the preview: https://deploy-preview-406--tag-app-delivery.netlify.app/
And I think Netlify should now be looking for changes in the whitepapers directories.

2023-11-27 12:27 UTC, joshgav commented
Hi @sysnet4admin - following #492 the website supports multiple languages, and so - sorry to have to ask :laughing: - but could we refactor this PR to be like #492 and have Korean as an additional supported language on the site?

cc @eeap who volunteered to help in <https://github.com/cncf/tag-app-delivery/issues/394#issuecomment-1827680971>

2023-11-27 12:39 UTC, sysnet4admin commented
@joshgav Sure! You may know that I would like to spread out useful information like this. Feel free to move forward!.

2023-11-28 00:17 UTC, sysnet4admin commented
@Eeap No problem totally. Any help or take over will highly welcome :) 
Please go for us

2024-01-31 13:45 UTC, abangser commented
Thanks for sticking with this @sysnet4admin !

I went to test this and I don't think the file is in the right location for the current hugo setup. I think if you instead move the file to replace this one the one at `website/content/ko/wgs/platforms/whitepaper/index.md` we will be able to get the translation on the site.

In addition, I saw that @Eeap is up for helping. @Eeap based on your hope to use this I gather you may also be a native Korean speaker? We usually try to have at least one other native speaker review the translations as we know that Google Translate isn't always the best at picking up nuance of real language use. Is that something you could help with?

I think those two bits are parallelisable and hopefully the last hurdles to getting this merged! 🤞

2024-02-01 04:17 UTC, sysnet4admin commented
Hi @abangser 
Thank you for your feedback. 

**1. index.ko.md**
First I already PR #406 before for index.ko.md. probably it would like to merge this `md` from current index.md right?
If it is Yes, I will progress from #406 during weekend. But I am wrong, feel free to let me know. 

As-IS: not merged yet (#406)
To-BE: website/content/ko/wgs/platforms/whitepaper/index.md

**2. localization** 
It looks like double-check by native-speaker when it uploaded or released? from other native-speaker. 
Yes I could be (if that's not a lot of burden at a once 😅)
@Eeap Any help as current thread?
OR
`parallelisable` may have issue? if it is right, I do just merge only index.ko.md for platforms-whitepaper(v1). 
So maybe @Eeap will lead other docs I guess. Is it right? @Eeap 

Anyway please don't be any frustrating to point out me.

2024-02-01 10:34 UTC, Eeap commented
Hi @abangser @sysnet4admin 

If you don't mind I think I can do other contents too. :) But I will be able to translate it maybe next weekend.
Also, I don't know exactly that I understood other things. 😅
Do you mean that if I translate other contents, I have to confirm from just one native korean speaker like @sysnet4admin ?? or more than one ??
Thanks you for suggesting this opportunity.

2024-02-03 01:39 UTC, sysnet4admin commented
@abangser 
I replaced `index.md` for platforms-whitepaper as you request. 
Please let me know any issue or further thing, feel free to let me know.  

@Eeap I merged your draft version which is changed the content's title. If you need to change from this translating version (from 8months ago), please let me know or PR from this version. 

FYR @joshgav  :)

2024-02-03 12:09 UTC, abangser commented
That's perfect @Eeap! So sorry for the delayed response but the change you made was exactly what I was suggesting and I have confirmed on a local build that I can now see the Korean version as expected.

Thanks for all your hard work on this!

I did also notice the update to the netlify.toml file. I am wondering if @joshgav or maybe @cjyabraham have knowledge on this and can confirm it is a setting we want to apply?

2024-02-04 02:35 UTC, cjyabraham commented
Hi @abangser, I've reverted the change to netlify.toml. It was done back last May and we've had more recent updates to it since then.

2024-02-04 13:05 UTC, Eeap commented
I think there is something to change about translation style. Because I used "~한다와 같은 평어체." in other contents for following common translation guide, It looks nice to change like this. @sysnet4admin
Also, Glossary page has been changed to another page.

2024-02-04 13:14 UTC, Eeap requested changes

2024-02-04 13:14 UTC, Eeap commented on website/content/ko/wgs/platforms/whitepaper/index.md
> +10. **사용자 인증 및 시크릿(Secret) 관리 서비스**: 서비스 및 사용자 ID 및 권한 부여, 인증서 및 키 발급, 정적 시크릿 저장소 제공
There is **Messaging** sentence in English page, I think you missed it. :)
If you don't mind, I will fix all of them like style, missing sentence. (And I will make a PR to your branch)

2024-02-14 02:04 UTC, sysnet4admin commented
@Eeap Thank you for notification. 
So I changed (to split each of purpose). `whitepaper/index.md` to `whitepaper/index.md` and `glossary/_index.md`
However I looks not latest version especially `glossary/_index.md`. Would you update to `latest`? to catch up the glossary?

2024-02-14 06:21 UTC, abangser commented
Hi all, thanks again for all the hard work on this translation. 

I just wanted to call out that the glossary has a PR open now for a facelift so if you are interested in updating you may want to refer to the options in [this comment](https://github.com/cncf/tag-app-delivery/pull/545#issuecomment-1925309424)!

2024-02-16 02:00 UTC, sysnet4admin commented
@Eeap Hi, 
I already hand over my documents. so you could modify whatever you want. Anyhow when I translate to some document, my point is ONLY to understand easily to user and community. Probably that's main reason why casual describing and more comment by my opinion (like extra information) 
Plus, glossary @abangser said it change a lot (i.e. facelift) you(@Eeap ) may follow up what you want. 
In my view, 2nd option is better but you may choose your own thought.

2024-02-16 04:26 UTC, Eeap commented
@sysnet4admin Hi :)
I understand what you said, so I did not touch translation style like extra information. I just have modified sentence closing style, and also created PR to your branch. Could you check it again??

> Plus, glossary @abangser said it change a lot (i.e. facelift) you(@Eeap ) may follow up what you want.
In my view, 2nd option is better but you may choose your own thought.
I have also checked this before, I think it is better to merge this PR(if there is no problem) and create another PR for total Platform WG's translation (It will follow up English contents, and change old version)

2024-02-17 00:10 UTC, sysnet4admin commented
@Eeap Thank you for your feedback. 
In my option, first merge and change or modify whatever you want that is better progress I think. 
I am not sure what you metion the `brance` but I do not modify anymore after publishing it. 
So you could take over after finishing this stage. i.e. you could chnage any kind of format or change type.

2024-02-17 04:19 UTC, Eeap commented
Okay, it's great :) Thanks for suggesting other options.
Then could you double check if I translate the contents, @sysnet4admin ?? 
Could you check this again, @abangser ?? It is better to create another PR for total Platform WGs translation.

2024-02-17 05:34 UTC, sysnet4admin commented
@Eeap I am not sure that you point me out. 
Anyhow here is my suggestion for understading each other. 
`Season1`: I finished this and merge(if it could). 
`Season2`: You(@Eeap) make your own episode. Because I am stuck from other job. (Work, Book and others)

2024-02-17 10:09 UTC, Eeap commented
Sounds Great :) Thank you @sysnet4admin

2024-02-23 10:31 UTC, abangser commented
Hey all. If I follow, it sounds like we want to try to merge this and then extend in another PR. That sounds like a great plan.

I believe we have two blockers for merging:
1. the DCO needs to be signed (I believe this is for you @sysnet4admin)
2. I am unable to build this locally, I worry that we need to rebase main on this branch, but that also didn't work locally so I am not sure if there is a bigger issue
3.  I believe the two keys [here](https://github.com/cncf/tag-app-delivery/pull/406/files#diff-b3ad2cc1c4d0018c3f8006dbe1b084051b1ff732eda4b25fb94f7f5c56df7108R2-R3) need to stay in english (changing this does not improve the issue in the 2nd point)

2024-02-25 00:48 UTC, sysnet4admin commented
Hi @abangser, 
I fix key value issue by abnormal work(KO..) as well as several conflict items. 
And I change 2 docs due to it already translate 11 months ago and there is not a lot of change at that moment. 
So in my view, merge it and take over @Eeap from this content. He/She already [agree](https://github.com/cncf/tag-app-delivery/pull/406#issuecomment-1949923798) this.
Thank you for your all of efforts.

2024-02-26 17:37 UTC, joshgav requested changes
From what I can tell the translations look great but the keys for some front matter need to stay in English, as I noted in comments. Let's fix those before we merge, thanks!

2024-02-26 17:37 UTC, joshgav commented on website/content/ko/wgs/platforms/whitepaper/index.md
> +제목:  "CNCF 플랫폼 백서(White Paper)"
It seems that the key here needs to stay in English, that is it should be "title:"

I say this cause in the current deployment preview no title is rendered for this section in the Korean version.

2024-02-26 17:37 UTC, joshgav commented on website/content/ko/wgs/platforms/whitepaper/index.md
> +버전_정보: https://github.com/cncf/tag-app-delivery/tree/main/platforms-whitepaper/README.md
This key should also probably staty in English as "version_info"

2024-02-26 17:37 UTC, joshgav commented on website/content/ko/wgs/platforms/whitepaper/index.md
> +설명: "이 백서는 기업 리더, 엔터프라이즈 아키텍트, 플랫폼 팀 리더가 클라우드 컴퓨팅을 위한 내부 플랫폼을 옹호하고, 조사하고, 계획할 수 있도록 지원하고자 합니다. 플랫폼은 기업의 실제 가치 흐름에 큰 영향을 미치지만 간접적으로만 영향을 미치므로 플랫폼 팀의 장기적인 지속 가능성과 성공을 위해서는 경영진의 합의와 지원이 필수적입니다. 이 백서에서는
Finally, this key should stay in English as "description".

2024-02-26 17:40 UTC, joshgav commented on website/content/ko/wgs/platforms/whitepaper/index.md
> +제목:  "CNCF 플랫폼 백서(White Paper)"
I fixed this!

2024-02-26 17:40 UTC, joshgav commented on website/content/ko/wgs/platforms/whitepaper/index.md
> +설명: "이 백서는 기업 리더, 엔터프라이즈 아키텍트, 플랫폼 팀 리더가 클라우드 컴퓨팅을 위한 내부 플랫폼을 옹호하고, 조사하고, 계획할 수 있도록 지원하고자 합니다. 플랫폼은 기업의 실제 가치 흐름에 큰 영향을 미치지만 간접적으로만 영향을 미치므로 플랫폼 팀의 장기적인 지속 가능성과 성공을 위해서는 경영진의 합의와 지원이 필수적입니다. 이 백서에서는
I fixed this

2024-02-26 17:41 UTC, joshgav approved these changes

2024-02-26 17:43 UTC, joshgav commented
I believe we've addressed the issues and this PR boils down to a proper Korean translation of the Platforms white paper and current Platforms glossary. With that I think we should go ahead and merge!

2024-02-26 17:44 UTC, merged

2024-02-26 17:45 UTC, joshgav commented
Thanks you @sysnet4admin, @Eeap and everyone else for all your work on this!