Enable  i18n with zh(Chinese)
cncf/tag-app-delivery pull request #450
Opened 2023-08-16 10:48 UTC by node

Use the latest website version (after #426 ).

2023-08-17 19:23 UTC, abangser commented
Hey @node , thanks for this PR! I am really excited to see us set this site up for multiple languages and specifically for the white paper 🎉

I used your preview link from [this comment](https://github.com/cncf/tag-app-delivery/pull/450#issuecomment-1680379495) and tried to navigate to the white paper and saw some behaviour I didn't expect.

Specifically, I followed this link path:
1. Open the home page, note that the language in the top right is `English`
2. Click on `Working Groups` in the top right
3. Click on `Platform Working Group` (recreated from both the main body of the page or the left hand side link)
4. Click `CNCF Platforms White Paper` from the left hand side

When this page loaded I saw a few things:
1. The language in the top right turned to `Chinese`
2. The language in the whole page was a mix (see attached screenshot)
3. I could not change the language back to `English`

This seems to be an issue only on the white paper page since the charter and other pages seem to allow both languages.

Can you please take a look and make the white paper experience the same as the other pages before we look to review / merge? Thanks!

2023-08-18 04:16 UTC, node commented
Hi @abangser  Thanks for your review and bring up the issue.  

I checked the config and found the key issue: there is a soft link under both content/en/wgs/platforms  and contene/zh/wgs/platforms , and they refer the same one file under platforms-whitepaper/latest . So we can not let this support i18n, better choice is copy it then translate . 

I will fix this later  😄

2023-08-21 04:18 UTC, node commented
Hi @abangser   The PR updated has fixed the issue.  The key point is the URL attribute setting in .MD file under whitepaper. 
Cancle that setting, everything is OK now.

2023-08-21 13:58 UTC, abangser commented
Amazing, thanks for the quick review @node 🙌 

Just want to confirm that this is to put in the drop down for language in the top right plus minimal title translations rather than any full document translations?

Assuming that is correct, I think that this is what I would expect and all looks good. I believe some of the people with repo permissions for merging may be on summer holiday so I apologise if this sits short bit, but I will attempt to chase as they come back.

2023-08-22 09:51 UTC, node commented
Correctly .  Only main menu and page/article titles are translated into Chinese.

By the way, as I know the platform whitepaper have been translated into Chinese by other guy, maybe we cloud suggest the translator submit here again after this PR merged.

2023-08-22 16:13 UTC, roberthstrand approved these changes
I looked through the preview deployment, and everything looks good. No broken links, that I can find at least.

2023-08-25 16:54 UTC, joshgav requested changes
Thanks @node for this work! Looks pretty good to me, except that originally the whitepaper directories were symlinks to the directories in the repo `operator-whitepaper/latest` and `platforms-whitepaper/latest`. Can we restore those symlinks for the English version?

Side note - I'm open to revisiting the symlink setup, if we want to do that let's open another issue to discuss.

Thanks again! And indeed, we'll ask the contributor of the Chinese translation to submit it here once this is merged.

2023-08-25 16:54 UTC, joshgav commented on website/content/en/wgs/operator/whitepaper/README.md
This directory should be a symlink to the top-level "operator-whitepaper/latest" directory.

2023-08-25 17:32 UTC, abangser commented on website/content/en/wgs/operator/whitepaper/README.md
Did we have latest? I thought we left it as vX so that it would stay stable for multiple languages as we added / evolved latest. 

That was my memory but also remember this being an interesting debate so please excuse me if I misremember!

2023-08-25 18:10 UTC, joshgav commented on website/content/en/wgs/operator/whitepaper/README.md
We did talk about that @abangser and could visit again, but it looks like we didn't implement it or it got reverted. Definitely open to making the change in another PR. My ask is to stick with the current arrangement for this PR; here's the symlink now: <https://github.com/cncf/tag-app-delivery/blob/main/website/content/wgs/platforms/whitepaper>

An interesting question this raises - should the whitepaper directories themselves be split into languages? Where will the official Chinese translation go - at the moment would it only be in the website directory?

2023-08-26 07:43 UTC, abangser commented on website/content/en/wgs/operator/whitepaper/README.md
Definitely happy to stay latest for this PR 👍

But also great shout on having confidence on where the translation files will go as a part of merging this one.

2023-08-27 13:10 UTC, node commented on website/content/en/wgs/platforms/whitepaper/index.md
Restore symlinks of two whitepapers under content/en .

2023-08-28 01:49 UTC, node commented on website/content/en/wgs/operator/whitepaper/README.md
That is really hard to keep latest version in multi languages without outer translation track system or tool. 

I think currently we choose english version as latest util there is a final version or relatively stable version, then sync to other language content dir. 

So I restore the symlinks under content/en and keep a copy version under content/zh .

2023-11-01 04:13 UTC, closed without merging

2023-11-01 13:00 UTC, joshgav commented
@node we still want to include these, I've just been waiting for some of our backlog to wrap up.

2023-11-02 01:42 UTC, node commented
> @node we still want to include these, I've just been waiting for some of our backlog to wrap up.

There are some conflicts in the previous PR, I will check and fix them then re-submit  a new PR.

2023-11-02 15:17 UTC, node commented
@joshgav  Make it this time, hard but successfully 😄      See #492

2023-11-02 15:54 UTC, joshgav commented
Thanks you @node! Taking a look.