WIP: maturity paper chinese version
cncf/tag-app-delivery pull request #502
Opened 2023-11-19 07:01 UTC by mouuii

2023-11-19 13:57 UTC, node commented
Hi @mouuii I think you are on the right way, please keep going on.  👋 
By the way,my advice about translation is : 
Based on your professional understanding, use free translation instead of literal translation and machine translation.

2023-11-20 09:22 UTC, mouuii commented
> Based on your professional understanding, use free translation instead of literal translation and machine translation

get

2023-11-21 09:56 UTC, pacoxu commented
@windsonsea @mengjiao-liu Do you have time to review this?

2023-11-21 10:43 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +CNCF 的首份 [平台定义白皮书](https://tag-app-delivery.cncf.io/whitepapers/platforms/) 描述了什么是云计算下的内部平台，以及该平台应为企业带来哪些价值。 但要实现这些价值，一个组织必须反思并刻意追求对它们有影响的成果和实践，同时记住每个组织都依赖于为其自身组织量身定制的内部平台 - 即使这个平台只是关于如何使用第三方服务的文档。 这
```suggestion
CNCF 的首份[平台定义白皮书](https://tag-app-delivery.cncf.io/whitepapers/platforms/) 描述了什么是云计算下的内部平台，以及该平台应为企业带来哪些价值。但要实现这些价值，一个组织必须反思并刻意追求对它们有影响的成果和实践，同时记住每个组织都依赖于为其自身组织量身定制的内部平台 - 即使这个平台只是关于如何使用第三方服务的文档。 这个成熟度模型提供了一个框架，用于反思和识别任何组织中改进的机会。
```
中文中标点和下一句话不用空一格，下同。

2023-11-21 10:43 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +受到 DevOps 承诺的跨职能合作的启发，平台和平台工程在企业中作为这种合作的明确形式出现。 平台策划并展示了常见的能力、框架和体验。 在这个工作组及其相关出版物的背景下，重点是那些促进和加速 [内部用户]({{< ref "/wgs/platforms/glossary#platform-users" >}})（如产品和应用团队）工作的平台。
```suggestion
受到 DevOps 承诺的跨职能合作的启发，平台和平台工程在企业中作为这种合作的明确形式出现。平台策划并展示了常见的能力、框架和体验。在这个工作组及其相关出版物的背景下，重点是那些促进和加速[内部用户]({{< ref "/wgs/platforms/glossary#platform-users" >}})（如产品和应用团队）工作的平台。
```

2023-11-21 10:43 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +随着平台工程在过去几年中的重要性日益突显，一些模式已经变得明显。 通过将这些模式和观察结果组织成一个渐进的成熟度模型，我们旨在引导\[平台团队]\({{< ref "/wgs/platforms/glossary#platform-teams" >}}) 关注他们可能面临的挑战和应对的机会。 每个方面都以各级不同小组和组织在各方面的连续特征加以描述。 我们期望读者能在模型中找到自己的位置，并识别
“\[平台团队]\” 这里为什么要使用”\“ ？

2023-11-21 13:08 UTC, node requested changes

2023-11-21 13:08 UTC, node commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +这是非常完美的！ 所有组织和团队都具有特定于它们的动态和参数。
> 这是非常完美的！所有组织和团队都具有特定于它们的动态和参数。

那可太好了！每个组织和团队都有其特定的动力和因素。

2023-11-21 13:08 UTC, node commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +请记住，本文的目标并不是要提供一种刻板的公式，而是一个您可以应用于您的情境的框架。 也许不是每个词都与您相关，但我们希望内容能激发您反思自己的平台之旅，吸取有意义的部分，而不必纠缠于其他部分。
> 吸取有意义的部分，而不必纠缠于其他部分。

考虑下这个方案：取其所需，舍其所弃。

2023-11-21 14:25 UTC, joshgav approved these changes
Rubber stamp LGTM, but please defer to Chinese speakers to confirm the content is ready before merging.

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- 当管理层对产生收入的功能没有施加压力时，工程师们被鼓励投资于提升能力的改进。 这意味着在一些sprint的最后几天，他们会优先考虑自动化和改进他们CI/CD流水线的某些部分。 这些改进往往是突发性的，因为可能有几个月的冲刺任务过于繁重，不能再这些方面花费时间
```suggestion
- 当管理层对产生收入的功能没有施加压力时，工程师们被鼓励投资于提升能力的改进。 这意味着在一些sprint的最后几天，他们会优先考虑自动化和改进他们CI/CD流水线的某些部分。 这些改进往往是突发性的，因为可能有几个月的冲刺任务过于繁重，不能再在这些方面花费时间
```

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- 功能移除是讨论的关键部分，目标是拥有一套受到良好支持、使用频繁的能力，而不是一片可能无法维护的庞大领域。
“well used” 翻译为 “使用频繁” 不是很对应，建议更新为 "良好使用"。

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- 新功能和增强功能通过Issues和PR进行协调。 文档和核对表使贡献者能够进行自我驱动的开发。
“Issues” -> “Issue” ，和 “PR” 的单复数保持一致

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +对于如何获得这些程序问题的解决方案都是考人们口口相传 这些创建这些的自定义程序的过程缺少标准化和一致性。 配置和使用平台服务可能需要能力平台开发者的大力支持。
```suggestion
对于如何获得这些程序问题的解决方案都是靠人们口口相传。这些创建这些的自定义程序的过程缺少标准化和一致性。配置和使用平台服务可能需要能力平台开发者的大力支持。
```

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- 表面上的“简单”请求变得复杂，是因为找出了遵循的正确过程
```suggestion
- 表面上的“简单”请求变得复杂，是因为找出了遵循的正确过程。
```
与前面保持一致，都添加句末标点。

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +提供解决办法的方式为用户提供自主权，几乎不需要维护者的支助。 组织鼓励并支持解决方案提供一致的接口，以实现用户体验在不同能力之间的可发现性和可移植性。 虽然是自定义解决方案，但是这仍需要团队的能有对应的认知和实现 为了快速提升这些经验，在组织内部可能有指导性和简化的内部语言，使用户能够更快地适应和整合平台能力。 这样的平台将产生以用户为中心、可自定义和一致的能力。
```suggestion
提供解决办法的方式为用户提供自主权，几乎不需要维护者的支持。组织鼓励并支持解决方案提供一致的接口，以实现用户体验在不同能力之间的可发现性和可移植性。虽然是自定义解决方案，但是这仍需要团队的能有对应的认知和实现。为了快速提升这些经验，在组织内部可能有指导性和简化的内部语言，使用户能够更快地适应和整合平台能力。 这样的平台将产生以用户为中心、可自定义和一致的能力。
```

2023-11-22 02:55 UTC, mengjiao-liu commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- 提供一个 API 来提取数据库的创建和维护，并为用户提供它们所需要的任何信息，以利用平台能力，例如连接字符串， 保密数据的位置和带有观察能力数据的仪表盘。
中文和英文字符之间是否要前后留空格？建议全文保持一致。我建议保留空格。

2023-11-22 06:03 UTC, windsonsea commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- **应用程序和产品开发者**：作为平台用户，希望更详细地了解他们可能对内部平台有何期望
```suggestion
- **首席技术官、副总裁和技术总监**：着眼于规划数字转型并从宏观上增强开发生产力的领导者
- **工程管理者**：寻求为工程师赋能在减少开销和提高效率方面有所作为的团队和个人
- **企业架构师**：纵览全栈现代化技术、为解决难题致力于提供有价值和解决方案导向的观点
- **平台工程师和平台产品经理**：努力为平台构建者和平台用户构建最佳体验的团队和个人
- **产品供应商和项目维护者**：希望设计工具并传达信息以使用户能够成功使用平台和功能的组织和工程师
- **应用和产品开发者**：作为平台用户，设法详细了解用户对内部平台期待的功能特性
```
follow en style，不需要加空行

2023-11-22 08:03 UTC, mouuii commented
@mengjiao-liu @node @windsonsea  resolved comments

2023-11-22 09:21 UTC, windsonsea commented on website/content/zh/wgs/platforms/platforms-maturity-model/v1/index.md
> +- **应用程序和产品开发者**：作为平台用户，希望更详细地了解他们可能对内部平台有何期望
没有改过来呀，你仔细看文字也有不少修改。你可以直接 copy/paste suggestions

2023-11-23 03:50 UTC, cubxxw commented
/lgtm

2023-11-23 03:50 UTC, cubxxw approved these changes

2023-11-23 04:09 UTC, node commented
LGTM

2023-11-23 04:10 UTC, node approved these changes

2023-11-27 03:54 UTC, mouuii commented
@joshgav  I think this PR is ready to be merged

2023-11-27 12:14 UTC, joshgav commented
Thank you @mouuii @node @mengjiao-liu @pacoxu @cubxxw @windsonsea for your reviews!

2023-11-27 12:14 UTC, merged