Introduce more guidance on getting start contributing
cncf/tag-app-delivery pull request #523
Opened 2023-12-20 10:48 UTC by abangser

We have made awesome strides by introducing more contributing guides to the website in #519.

This closes #495 by introducing both a detailed blog post and an accompanying issue template which can support organising people's thoughts and provide the TAG with more information to support new ideas.

This is heavily modelled after the sandbox template but of course needs to be much more light weight. One thing that has been removed but may need to be re-added is a reference to who owns IP from any contribution.

Big thanks to @techmaharaj for a lot of the content and the first review of this PR.

2023-12-20 10:59 UTC, techmaharaj reviewed
Looks good to go. Left minor suggestions.

2023-12-20 10:59 UTC, techmaharaj commented on website/content/en/blog/contributing-to-wg-platforms.md
> +author: Abby Bangser & Atul Sharma
```suggestion
author: Abby Bangser & Atulpriya Sharma
```

2023-12-20 10:59 UTC, techmaharaj commented on website/content/en/blog/contributing-to-wg-platforms.md
> +This will present you with a templated issue where you can follow the prompts. You will first need to write a descriptive title, then answer each of the questions in the description field. If you fin
```suggestion
The GitHub issue will present you with a template where you can follow the prompts. First, You must write a descriptive title, then answer each question in the description field. If you find one is not relevant that is OK, write that and there is always a chance to chat more on these things after your initial submission.

For Slack, you can start a new thread in this format: [Proposal]<My_New_Idea>
```

2023-12-20 10:59 UTC, techmaharaj commented on website/content/en/blog/contributing-to-wg-platforms.md
> +What next?
```suggestion
## What next?
```

2023-12-20 11:34 UTC, lianmakesthings requested changes
Love this! Thanks so much for your work.

One thing: the "Getting started with contributing in WG Platforms" doesn't seem to show up in the deploy preview. Not sure what's going on there. Maybe I'm missing something.

2023-12-20 14:02 UTC, RobertKelly commented
Very detailed with encouraging guidance. Looks great to me! :shipit:

2023-12-20 21:17 UTC, abangser commented
Doh! @lianmakesthings I made an assumption that it would take some time to get reviews so I post-dated it to Dec 22. This meant it wouldn't show up on the blog. I just updated the date to today and confirmed locally that it shows up now. The preview should also be up soon!

2023-12-20 23:32 UTC, lianmakesthings commented
> Doh! @lianmakesthings I made an assumption that it would take some time to get reviews so I post-dated it to Dec 22. This meant it wouldn't show up on the blog. I just updated the date to today and confirmed locally that it shows up now. I expected a preview deploy to occur again but it keeps coming up as canceled 🤔 This may need to be either on trust or verified locally. So sorry!
No worries. Maybe you could just put the PR in draft mode if you're not ready for an "official" review yet. I tend to try to get reviews out of the way asap, so maybe I'm just too quick (or too thorough 😂 )

2023-12-21 08:04 UTC, abangser commented
This was definitely ready for review. I just didn't realise that was how the dates worked :til:

So there are two things I guess... 1) is the content reasonable and 2) does it show up on the site. Unfortunately the preview deploy isn't coming up for my change and I am not sure why not. So for #2 it unfortunately can only be validated locally 😢

2023-12-21 14:29 UTC, lianmakesthings commented
@joshgav @cjyabraham I remember you were trying to figure out why new commits in a PR don't trigger a rebuild of the deploy preview. Did you come to any solutions?

2023-12-21 15:52 UTC, cjyabraham commented
The deploy preview is here: https://deploy-preview-523--tag-app-delivery.netlify.app/blog/contributing-to-wg-platforms/

I'm not sure why netlify is reporting that the deploy is cancelled since it is built and seems up-to-date to me. You can find the link to deploy previews by inspecting a commit and clicking on "Details":
![Screenshot 2023-12-21 at 7 51 30 AM](https://github.com/cncf/tag-app-delivery/assets/463160/c1e0b605-d6cf-47ea-891d-cad429c73b10)

2023-12-21 20:04 UTC, lianmakesthings approved these changes

2023-12-21 22:20 UTC, merged