Minor fix for slack channel name
cncf/tag-app-delivery pull request #527
Opened 2023-12-26 16:14 UTC by r0mdau

2023-12-27 18:24 UTC, lianmakesthings approved these changes

2023-12-27 18:31 UTC, lianmakesthings requested changes
Thanks for the PR @r0mdau.
Would you mind changing it [here](https://github.com/cncf/tag-app-delivery/blob/8e21ec8f222180874ea0dd958bc17422cd9feb93/website/content/en/wgs/platforms/_index.md?plain=1#L9) too? It seems like we're not using the /about section on the website.

2023-12-27 20:51 UTC, r0mdau commented
> Thanks for the PR @r0mdau. Would you mind changing it [here](https://github.com/cncf/tag-app-delivery/blob/8e21ec8f222180874ea0dd958bc17422cd9feb93/website/content/en/wgs/platforms/_index.md?plain=1#L9) too? It seems like we're not using the /about section on the website.

Thanks for the review, I used an IDE this time and made all the appropriate changes.

2023-12-28 10:00 UTC, lianmakesthings approved these changes

2023-12-28 10:42 UTC, thschue approved these changes
lgtm

2023-12-28 11:42 UTC, abangser approved these changes

2023-12-28 14:02 UTC, merged