docs(platforms): change sentences in platforms whitepaper & add missing maturity-model contents in ko
cncf/tag-app-delivery pull request #646
Opened 2024-05-05 03:17 UTC by Eeap

According to #641, I have translated it into Korean. Also I have changed wrong sentences(like missing img, words..) and added missing documents about maturity-model contents in kor platforms.

Thank you :)

2024-05-05 09:07 UTC, abangser requested changes
Thanks for getting to this so quickly @Eeap!

As with any other translation, we will just look for another fluent speaker to review/approve before merging.

In addition, I noticed that you have copied the english version of a page into `website/content/ko/wgs/platforms/maturity-model/v1/index.md`. I believe at this point we have this being done automatically if the page is not yet translated for the language. Is there something you noted that required this?

2024-05-06 04:26 UTC, Eeap commented
> In addition, I noticed that you have copied the english version of a page into website/content/ko/wgs/platforms/maturity-model/v1/index.md. I believe at this point we have this being done automatically if the page is not yet translated for the language. Is there something you noted that required this?

Could I translate it with this PR until 8 May? Also, I know that another reviewer need for double checking.. 
I will find someone for checking as soon as possible :)

2024-05-08 10:01 UTC, Eeap commented
@abangser I have translate it with Korean, but "Notice i18n task" is failed because of different content of en(never touched). Could you check this one ??

2024-05-08 11:32 UTC, sysnet4admin commented
@Eeap Unfortunately, I have no time to contribute it anymore. you may consider with other member if you would like to review it.

2024-05-08 16:28 UTC, Eeap commented
Okay, I got it. Thank you :)

2024-05-13 11:26 UTC, Eeap commented
@abangser I have posted post for seeking people who would check it in [linkedIn](https://www.linkedin.com/posts/eeap_docsplatforms-change-sentences-in-platforms-activity-7194202342659936256-5Koj?utm_source=share&utm_medium=member_desktop), but it takes some time for seeking 🥲.

2025-09-09 15:34 UTC, closed without merging