Add missing picture to the platform white paper Chinese version
cncf/tag-app-delivery pull request #648
Opened 2024-05-10 06:51 UTC by node

The image translation work is shared at https://docs.google.com/presentation/d/16AeFfd8JG5aJYuTYPn30zNCKiuAnc7hEheRLQwGWHH8/edit?usp=sharing

Refer PR #623

2024-05-11 14:13 UTC, lianmakesthings requested changes
LGTM except for that empty file

2024-05-11 14:13 UTC, lianmakesthings commented on website/content/zh/wgs/platforms/whitepaper/assets/.empty
This file should be removed

2024-05-13 15:04 UTC, node commented
Sincerely invite @rootsongjc  to help review this image if he is free.  😄

2024-05-28 08:52 UTC, roberthstrand approved these changes

2024-05-28 08:55 UTC, roberthstrand commented
While it looks technically correct, I will post this is the CNCF Ambassador channel to see if any native speakers could give it a once-over before merging.

2024-05-28 11:48 UTC, node commented
Update: 
Add drawio raw file in Chinese while update PNG file .    Many thanks to @addozhang for your advice and help.

2024-05-28 12:40 UTC, roberthstrand commented
@node, Could you take a look at the comments left by @tao12345666333? I can't really judge whether one word is right or the other, so this is something that I need your help on.

2024-05-29 03:18 UTC, node commented
> @node, Could you take a look at the comments left by @tao12345666333? I can't really judge whether one word is right or the other, so this is something that I need your help on.

Fixed all of them. Please check it again @tao12345666333 , and thanks for your review.

2024-05-30 09:29 UTC, roberthstrand approved these changes

2024-05-30 09:30 UTC, merged