[WIP] Translate the Platform Engineering Maturity Model into Japanese
cncf/tag-app-delivery pull request #677
Opened 2024-06-10 12:32 UTC by hhiroshell

2024-06-11 13:24 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +    .filter(el => el.textContent === decodeURI(fragment))
This change makes the tab switcher of the model table work even if the tab names are written in multi-byte characters.

2024-06-11 13:27 UTC, hhiroshell commented
@nao @Okabe-Junya @kaitoii11 
Could you please review this when you have a moment?

2024-06-11 13:34 UTC, Okabe-Junya commented
maybe @naonishijima??

2024-06-11 14:57 UTC, hhiroshell commented
@Okabe-Junya 
Thank you for pointing that out. 😅

2024-06-12 09:57 UTC, naonishijima reviewed
I have some comment.

2024-06-12 09:57 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* プロバイダーによって管理された（いわば「クラウド」）サービスは、一貫性のない方法で採用され、使用されており、標準的なプラクティスやポリシーがなく、内部設定は見つけにくく、使いにくいです。
プロバイダーによって管理された（いわば「クラウド」）サービスは、一貫性のない方法で採用され、使用されており、標準的なプラクティスやポリシーがなく、内部設定は見つけにくく、使いにくいです。
Suggestion ↓
プロバイダーによって管理された（いわば「クラウド」）サービスは、一貫性のない方法で採用され、使用されており、内部構成が不明確で使いにくいため標準的なプラクティスやポリシーがありません。

2024-06-12 09:57 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* ある程度の外的な動機がプラットフォーム機能の使用につながります。例えば：
This is OK, but I prefer "〜活用につながります。" instead of "〜使用につながります。"

2024-06-12 09:57 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +### レベル2、戦略的である - 中央による追跡
Umm..
I don't have an answer but "Centrally tracked=中央による追跡" doesn't feel right.
The same applies to other words with Centrally.

2024-06-13 11:01 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +プラットフォームチームは、基本的な機能を超えて、組織全体の効率と効果を高める方法を見つけます。プラットフォームのコアメンテナは、新製品の市場投入までの時間を最適化し、企業全体のコストを削減し、新しいサービスへのガバナンスとコンプライアンスの効率的な適用を可能にし、ワークロードを迅速かつ容易にスケールする、などの横断的な要件を意図的に追求しています。これらのコアメンテナは、能力のスペシャリストが、
The only product teams here are "製品チーム". The other places are "プロダクションチーム".

2024-06-14 16:39 UTC, kaitoii11 requested changes

2024-06-14 16:39 UTC, kaitoii11 commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* 少量のデータに依存する
```suggestion
* 少量のデータに頼る
```

2024-06-17 12:08 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +プラットフォームエンジニアリングがここ数年で注目されるようになると、いくつかのパターンが明確になってきました。これらのパターンと観察を漸進的な成熟度モデルにまとめることで、[プラットフォームチーム]({{< ref "/wgs/platforms/glossary#プラットフォームチーム" >}})を直面するかもしれない課題や目指すべき目標へと向けることを目指しています。
Thank you for your suggestion. I've simply applied. https://github.com/cncf/tag-app-delivery/pull/677/commits/f33cb5006a3216dbbf926f9b44264f1542d7e8d3

2024-06-17 12:08 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +プラットフォームの実装が組織ごとに異なることを認識することも重要です。 _あなたの_ 組織のクラウドネイティブへの変革の現状を評価することを確実に行ってください。この評価に活用できる素晴らしいリソースは、[Cloud Nativeの成熟度モデル](https://maturitymodel.cncf.io/)です。
Thank you for your suggestion. I've simply applied. https://github.com/cncf/tag-app-delivery/pull/677/commits/f33cb5006a3216dbbf926f9b44264f1542d7e8d3

2024-06-17 12:09 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* プロバイダーによって管理された（いわば「クラウド」）サービスは、一貫性のない方法で採用され、使用されており、標準的なプラクティスやポリシーがなく、内部設定は見つけにくく、使いにくいです。
Thank you for your suggestion. I've simply applied. https://github.com/cncf/tag-app-delivery/pull/677/commits/f33cb5006a3216dbbf926f9b44264f1542d7e8d3

2024-06-17 12:09 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* ある程度の外的な動機がプラットフォーム機能の使用につながります。例えば：
Thank you for your suggestion. I've simply applied. https://github.com/cncf/tag-app-delivery/pull/677/commits/f33cb5006a3216dbbf926f9b44264f1542d7e8d3

2024-06-17 12:09 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* 仮想マシンのユーザーは、バージョンアップグレードに関する管理を一切行う必要がありません。求められるのは、彼らのデリバリーパイプラインに、代表的なスモークテストを含むステージを用意することだけです。	その後、アプリケーションのリスク許容度が低いためより強化されたアップグレード方法を待つか、またはリスク許容度が高いのでアーリーアダプターになるかを宣言するよう求められます。そして、仮想マシンの能力
Thank you for your suggestion. I've simply applied. https://github.com/cncf/tag-app-delivery/pull/677/commits/f33cb5006a3216dbbf926f9b44264f1542d7e8d3

2024-06-17 12:21 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +プラットフォームチームは、基本的な機能を超えて、組織全体の効率と効果を高める方法を見つけます。プラットフォームのコアメンテナは、新製品の市場投入までの時間を最適化し、企業全体のコストを削減し、新しいサービスへのガバナンスとコンプライアンスの効率的な適用を可能にし、ワークロードを迅速かつ容易にスケールする、などの横断的な要件を意図的に追求しています。これらのコアメンテナは、能力のスペシャリストが、
It seems natural to use "プロダクトチーム" in places it appears with "サービスチーム" or "アプリケーションチーム."
So, I will standardize it to "プロダクトチーム."

2024-06-17 12:23 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +プラットフォームチームは、基本的な機能を超えて、組織全体の効率と効果を高める方法を見つけます。プラットフォームのコアメンテナは、新製品の市場投入までの時間を最適化し、企業全体のコストを削減し、新しいサービスへのガバナンスとコンプライアンスの効率的な適用を可能にし、ワークロードを迅速かつ容易にスケールする、などの横断的な要件を意図的に追求しています。これらのコアメンテナは、能力のスペシャリストが、
Done 👍 https://github.com/cncf/tag-app-delivery/pull/677/commits/dd7e677508492d6d7c032b03f170df21523fa4fd

2024-06-18 03:44 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +### レベル4、最適化している - 統合されたサービス
@kaitoii11 

The latest Maturity Model uses "Integrated Service" here. So let's not change it.
https://github.com/cncf/tag-app-delivery/blob/a3c4e796b33814ea570475104054ca53f347d693/platforms-maturity-model/v1/index.md?plain=1#L322

2024-06-18 12:22 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +### レベル2、戦略的である - 中央による追跡
@naonishijima 

I have two alternatives for the translation of "Centrally," 「一元的な」 and 「中央集権的な」.

- 中央集権的な
  - centrally tracked: 中央集権的な追跡
  - centrally documented: 中央集権的な文書化
  - centrally enabled: 中央集権的な支援
  - centrally registered: 中央集権的な登録
  - centrally orchestrated: 中央集権的な統制
- 一元的な
  - centrally tracked: 一元的な追跡
  - centrally documented: 一元的な文書化
  - centrally enabled: 一元的な支援
  - centrally registered: 一元的な登録
  - centrally orchestrated: 一元的な統制

I think "中央集権的な" is more natural than other options, even though the dictionaries don't provide such a meaning.

2024-06-18 13:06 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +持続的に人的およびリソース的なサポートをするために、予算と人員が割り当てられます。割り当てられた人員は、ソフトウェアデリバリーの高速化のために一般的に必要とされる一連の機能を提供する任務を負います。これらのチームはしばしば、技術的な要求を、受け身的に満たすことに焦点を当てます。彼らはDevOps、エンジニアリング支援、開発者体験（DevExまたはDevX）、共有ツール、センター・オブ・エクセレン
Fixed. I appreciate your good suggestion. 🙏 https://github.com/cncf/tag-app-delivery/pull/677/commits/07e44d5578ea6df2a2430a677875f2a17df06faa

2024-06-18 14:01 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +[プラットフォームエンジニアリング]({{< ref "/wgs/platforms/glossary#プラットフォームエンジニアリング" >}})とは、開発者やユーザーに対してそのようなコンピューティングプラットフォームを計画し提供するプラクティスです。これには、プラットフォームおよびその能力の総体、つまり人、プロセス、ポリシー、テクノロジーに加え、それらを推進するために望まれるビジネス成果も
"プラクティス" is good for me, too.

2024-06-18 14:02 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +### レベル2、戦略的である - 中央による追跡
"中央集権的な" is good for me!

2024-06-19 01:56 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +### レベル2、戦略的である - 中央による追跡
Thanks, I've fixed it here. https://github.com/cncf/tag-app-delivery/pull/677/commits/f2774fe59007b7eb2d31f7c07746af6bc7c1b599

2024-06-19 01:57 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +[プラットフォームエンジニアリング]({{< ref "/wgs/platforms/glossary#プラットフォームエンジニアリング" >}})とは、開発者やユーザーに対してそのようなコンピューティングプラットフォームを計画し提供するプラクティスです。これには、プラットフォームおよびその能力の総体、つまり人、プロセス、ポリシー、テクノロジーに加え、それらを推進するために望まれるビジネス成果も
Thanks, I've fixed it. https://github.com/cncf/tag-app-delivery/pull/677/commits/2a3dcaec672871f623998a8ef50ae2957d5ea8e4

2024-06-19 02:19 UTC, hhiroshell commented
To Reviewers:
All comments from Japanese speakers have been resolved. Could you please begin the final reviews?

2024-06-20 05:01 UTC, naonishijima commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* アプリケーション/サービスチームのユーザーは、プラットフォームの機能に対して修正、機能追加、フィードバックを提供できるようになっています。
Regarding this point 「プラットフォームの機能に対して修正、機能追加、〜」
What are the different features and capabilities?
is it the same(機能), or capabilities is "能力," and the feature is "機能"?

2024-06-20 06:36 UTC, abangser commented
Hey @hhiroshell this is great work and thank you to all of the reviewers as well! 

I am away from a computer until next week, but hopefully @roberthstrand / @krumware can take a look 🙌

2024-06-21 07:07 UTC, hhiroshell commented on website/content/ja/wgs/platforms/maturity-model/v1/index.md
> +* アプリケーション/サービスチームのユーザーは、プラットフォームの機能に対して修正、機能追加、フィードバックを提供できるようになっています。
I've transrated "capabilities" and "features" following the guidelines outlined in the translator's note.

https://github.com/cncf/tag-app-delivery/blob/2a3dcaec672871f623998a8ef50ae2957d5ea8e4/website/content/ja/wgs/platforms/maturity-model/v1/index.md?plain=1#L505

I think it's a mistranslation. The word 'capabilities' in the sentence should be translated to '能力'.

2024-06-28 12:35 UTC, hhiroshell commented
@roberthstrand, @krumware 

All comments from Japanese speakers have been resolved. Can we please proceed to the final reviews?
Please let me know if you have any concerns, and I will gladly try to resolve them.

2024-06-28 12:52 UTC, krumware commented
Thanks! It looks like the branch needs to be updated with the latest changes from the main branch. Are you able to resolve that?

2024-06-28 13:05 UTC, hhiroshell commented
@krumware 
I'm sorry, I missed that. 🙏 The issue has been resolved, so please check it.

2024-07-01 12:08 UTC, roberthstrand approved these changes

2024-07-01 12:08 UTC, merged