Translate in French the Platforms Glossary
cncf/tag-app-delivery pull request #693
Opened 2024-06-19 20:33 UTC by mathieu-benoit

2024-07-10 12:55 UTC, antoine-sncf reviewed
Review of the first part.
Next part will continue at `Utilisateurs de la Plateforme `

2024-07-10 12:55 UTC, antoine-sncf commented on website/content/fr/wgs/platforms/glossary/_index.md
> +## Ingénierie de Plateforme
Il y aurait il besoin d'un pluriel en vesion francaise ?
```
Ingénierie des Plateformes
Ingénierie de Platformes
```

2024-07-10 12:55 UTC, antoine-sncf commented on website/content/fr/wgs/platforms/glossary/_index.md
> +La conception, la construction, l’exploitation et l’évolution d’une plateforme. Une façon de considérer la pratique est de la considérer comme une approche axée sur l'empathie en matière de conceptio
`La conception, construction, exploitation et évolution d’une plateforme.`

2024-07-10 12:55 UTC, antoine-sncf commented on website/content/fr/wgs/platforms/glossary/_index.md
> +La conception, la construction, l’exploitation et l’évolution d’une plateforme. Une façon de considérer la pratique est de la considérer comme une approche axée sur l'empathie en matière de conceptio
J'ai une préférence à utiliser le terme `technico-sociale` mais le terme `sociotechnique` est je pense valide.
Ex: "le platforme engineering est une discipline technico-sociale". Cela permet de souligner une double facette technique et sociale alors que sociotechnique me fait plus penser à uniquement la facette sociale

2024-07-10 12:55 UTC, antoine-sncf commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
` pour atteindre ces objectifs.`
je trouve qu'il manque l'aspect "simplifier" du "facilitate"
` pour faciliter l'atteinte de ces objectifs.`

2024-07-15 11:29 UTC, sestegra requested changes

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +En fonction de la portée et de l'audience d'une plateforme, elle peut parfois être appelée “Plateforme de Développement”, “Plateforme de Développement Interne (IDP)”, “Plateforme de Livraison”, “Plat
Je préfère également "périmètre"

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +## Ingénierie de Plateforme
Pour la version française, je laisserai la version au singulier.
Si vous choississez de conserver le pluriel, la suggestion "Ingénierie de Platformes" est la plus adaptée.

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +En fonction de la portée et de l'audience d'une plateforme, elle peut parfois être appelée “Plateforme de Développement”, “Plateforme de Développement Interne (IDP)”, “Plateforme de Livraison”, “Plat
La virgule avant "mais" est conseillée pour marquer un arrêt.
"solution de plateforme plus gérée, mais souvent moins personnalisable"

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Je suggère une virgule avant "du" dans la phrase
"le processus complet, du développement d’une application jusqu’aux opérations en production"

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes qui utilisent directement les fonctionnalités de la plateforme, y compris, mais sans s'y limiter, les développeurs d'applications, les opérateurs d'applications, les scientifiques de do
Typo s/quiconque deploie/quiconque déploie/

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
La tournure au pluriel me semble plus approprié ici également.

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Idem remarque au-dessus, les prépositions sont nécessaires

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Je propose la tournure suivante:
"l'ingénierie de plateforme se distingue par son accent mis sur la création d'une infrastructure concrète — la plateforme elle-même — pour faciliter ces objectifs."

2024-07-15 11:29 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Cf remarque précédente

2024-07-15 11:33 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les avantages spécifiques pour les utilisateurs, ou **_qu'est ce qu'_** une plateforme fournit. Celles-ci ne doivent pas être confondues avec les qualités de la plateforme qui décrivent **_comment_**
Typo s/qu'est ce que/qu'est-ce que/

2024-07-15 20:00 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +En fonction de la portée et de l'audience d'une plateforme, elle peut parfois être appelée “Plateforme de Développement”, “Plateforme de Développement Interne (IDP)”, “Plateforme de Livraison”, “Plat
"périmètre" et "," avant le "mais" en place maintenant.

2024-07-15 20:00 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Ensemble de fonctionnalités, de documentations et d'outils qui supportent le développement, le déploiement, l'exploitation et/ou la gestion de la livraison de produits et de services. Une plateforme
Good catch, done.

2024-07-15 20:02 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Ensemble de fonctionnalités, de documentations et d'outils qui supportent le développement, le déploiement, l'exploitation et/ou la gestion de la livraison de produits et de services. Une plateforme
J'ai garde les preposition "de", meme si repetitive, je pense que c'est mieux.

Done pour la partie "Lorsque les plateformes sont bien conçues, elles".

2024-07-15 20:05 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Si vous souhaitez faire référence à ces définitions en dehors du cadre des documents du groupe de travail, veuillez noter qu'elles ont été rédigées dans le contexte du TAG de la livraison d'applicati
Bon point, j'y suis alle avec "elles ont été rédigées dans le contexte CNCF et livraison d'applications". Pour etre coherent avec le reste.

2024-07-15 20:05 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +## Ingénierie de Plateforme
J'ai garde la version singulier, en anglais ce n'est pas Platforms.

2024-07-15 20:06 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +La conception, la construction, l’exploitation et l’évolution d’une plateforme. Une façon de considérer la pratique est de la considérer comme une approche axée sur l'empathie en matière de conceptio
Simplification faite.

2024-07-15 20:08 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +La conception, la construction, l’exploitation et l’évolution d’une plateforme. Une façon de considérer la pratique est de la considérer comme une approche axée sur l'empathie en matière de conceptio
Bon point, mis en place maintenant.

2024-07-15 20:09 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +La conception, la construction, l’exploitation et l’évolution d’une plateforme. Une façon de considérer la pratique est de la considérer comme une approche axée sur l'empathie en matière de conceptio
Bons point, maintenant en place.

2024-07-15 20:11 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
Done.

2024-07-15 20:12 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
Done.

2024-07-15 20:13 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
Done.

2024-07-15 20:14 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
Bon point, done.

2024-07-15 20:16 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
"advocates" peut etre quelque chose autour d'"evangeliste" aussi si "représentants" ne parait pas bien.

tech writer sont celles et ceux qui ecrivent de la doc technique.

2024-07-15 20:18 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Je viens de le mettre au pluriel, mais il faudrait peut etre aller changer a la source aussi ? J'ai directemetn prise ca d'ici https://glossary.cncf.io/fr/devops/. @sestegra, veux-tu voir ca dans vos travaux FR sur la glossaire global ?

2024-07-15 23:43 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes qui utilisent directement les fonctionnalités de la plateforme, y compris, mais sans s'y limiter, les développeurs d'applications, les opérateurs d'applications, les scientifiques de do
Good catch, done.

2024-07-15 23:44 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les avantages spécifiques pour les utilisateurs, ou **_qu'est ce qu'_** une plateforme fournit. Celles-ci ne doivent pas être confondues avec les qualités de la plateforme qui décrivent **_comment_**
Good catch, done.

2024-07-15 23:47 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Gotcha, done.

2024-07-15 23:47 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Done.

2024-07-16 00:05 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Je les ai gardees.

2024-07-16 00:12 UTC, mathieu-benoit commented on website/config.toml
> +description = "Le TAG App Delivery se concentre sur la mise en oeuvre de projets et d'initiatives liés à la livraison d'applications cloud natives, comprenant leur création, déploiement, gestion et e
Bon point, done.

2024-07-16 00:14 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Desole, a quel endroit ?

2024-07-16 00:18 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
Bon point, rectifie.

2024-08-02 01:20 UTC, mathieu-benoit commented
Thanks again @sestegra and @antoine-sncf for your first review. Gentle bump for the second review, for my updates and the rest. Thanks!

2024-08-29 16:23 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Cool, merci ! Aussi si tu veux je peux ouvrir une PR directement la-bas ?

2024-08-29 16:34 UTC, sestegra requested changes

2024-08-29 16:34 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle les équipent gèrent le processus complet du développement d'une application jusqu'aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr
Typo s/équipent/équipes/

Pour les "mises en oeuvre", mettre le e dans l'o. "mises en œuvre"

2024-08-29 16:34 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
type s/des exploitant/des exploitants/

et je ne mettrais pas de majuscule à Responsable produit, il est déjà en gras.
La tendance à mettre la première lettre en anglais n'est pas fréquente en français, car la majuscule a un sens en français comme "l'Histoire" ou "l'histoire".

2024-08-29 16:34 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les avantages spécifiques pour les utilisateurs, ou **_qu'est-ce qu'_** une plateforme fournit. Celles-ci ne doivent pas être confondues avec les qualités de la plateforme qui décrivent **_comment_**
Idem "mise en œuvre"

2024-08-29 16:36 UTC, sestegra commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
PR déjà faite https://github.com/cncf/glossary/pull/3309

2024-08-29 16:39 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +“Le DevOps est une méthodologie dans laquelle une équipe gère le processus complet du développement d’une application jusqu’aux opérations en production.”<sup><a href="https://glossary.cncf.io/fr/dev
Super, merci ! Too fast! ;)

2024-10-01 19:16 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les personnes responsables de la construction et de la gestion de la ou des plateformes. Les membres de l'équipe de la plateforme comprennent des **ingénieurs de plateforme**, qui se concentrent sur
Good points, done, thanks!

2024-10-01 19:20 UTC, mathieu-benoit commented
Thanks @sestegra, much appreciated! Anything else?

@antoine-sncf, over to you? ;) Thanks!

The goal would be to approve/merge this before the beginning of November if possible.

2024-10-02 04:48 UTC, sestegra commented
I finished the review

2024-10-02 07:52 UTC, antoine-sncf commented
I'll take time this friday (sorry september was a complete chaos here)

2024-10-18 13:30 UTC, Sheepux requested changes
Revue complète ! Signale moi pour une relecture ultime du document avant que je ne valide :)

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Les avantages spécifiques pour les utilisateurs, ou **_qu'est-ce qu'_** une plateforme fournit. Celles-ci ne doivent pas être confondues avec les qualités de la plateforme qui décrivent **_comment_**
`durables` -> `pérennes`

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Un groupe de personnes qui développent et maintiennent une fonctionnalité offerte par la plateforme. Les fournisseurs peuvent être des organisations externes ou des équipes internes et, dans les peti
> qui développent également la plateforme plus large

`qui développent aussi plus largement la plateforme`

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Un groupe de personnes qui développent et maintiennent une fonctionnalité offerte par la plateforme. Les fournisseurs peuvent être des organisations externes ou des équipes internes et, dans les peti
> d’abstractions pour les fournisseurs 
`d'abstractions vis à vis des fournisseurs`

> le "verrouillage"
je rajouterai (lock-in) derrière car parle beaucoup plus coté IT.

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Un groupe de personnes qui développent et maintiennent une fonctionnalité offerte par la plateforme. Les fournisseurs peuvent être des organisations externes ou des équipes internes et, dans les peti
leur plateforme viable la plus petite (TVP)
Je laisserai le terme TVP en anglais, pas besoin de traduire mot à mot ici. On parle de MVP au quotidien, ca ne me gène pas.

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Fait référence à **_comment_** la plateforme et ses fonctionnalités fonctionnent et ce à quoi on peut s'attendre en termes d'exigences fonctionnelles ou non fonctionnelles. Les exemples incluent la f
> la sécurité qui peut être mesurée 

`pourrait être`

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Une quantification des coûts mentaux pour un utilisateur avant qu'il puisse bénéficier des fonctionnalités d'une plateforme. Il existe en fait trois types de charge cognitive : pertinente, intrinsèqu
J'utiliserai un `ne` néplétif (ne modifie pas le sens)
`avant qu'il ne puisse bénéficier`

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Une quantification des coûts mentaux pour un utilisateur avant qu'il puisse bénéficier des fonctionnalités d'une plateforme. Il existe en fait trois types de charge cognitive : pertinente, intrinsèqu
> avant qu'il puisse bénéficier des fonctionnalités d'une plateforme

au singulier (la charge mentale pour une seule fonction)
`bénéficier d'une fonctionnalité de la plateforme`

2024-10-18 13:30 UTC, Sheepux commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Un concept initialement défini dans le livre _Team Topologies_ par Matthew Skelton et Manuel Pais, qui encourage les organisations à trouver un équilibre judicieux entre une plateforme petite mais ef
Ne pas traduire `routinely' par "régulièrement". L'idée est plus de plutôt souligner le coté habitude (routine)
> et à prendre l'habitude d'intégrer des fournisseurs de fonctionnalités externes

2024-10-22 12:42 UTC, mathieu-benoit commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Une interface Web qui fournit un accès centralisé à une variété de ressources, d'outils et de services. Il peut servir de point de départ à un large éventail d'utilisateurs afin de gérer et d'interag
Je garde eventail, cela me semble plus francais.

2024-10-22 12:47 UTC, antoine-sncf commented on website/content/fr/wgs/platforms/glossary/_index.md
> +Un groupe de personnes qui développent et maintiennent une fonctionnalité offerte par la plateforme. Les fournisseurs peuvent être des organisations externes ou des équipes internes et, dans les peti
Utilise "la plus fine" alors (thinnest) plutôt que "petite" (smallest)

2024-10-22 13:16 UTC, mathieu-benoit commented
Sorry, I just messed up with a rebase, so closing this one for a cleaner and new PR taking all the suggestions/updates into account: https://github.com/cncf/tag-app-delivery/pull/761.

2024-10-22 13:16 UTC, closed without merging